### ISSUE TITLE
World spawn has priority

### ISSUE THREAD

**Issue by sammyt291** [Bammerbom/UltimateCore#10]
Hello,
The World spawn seems to have priority over beds/sethome.
I do not see anywhere to have the priority as beds then home then spawn anywhere?

This would be a fantastic addition for me as I run a survival server with strictly no teleportation.

Hope to see it fixed/added,
-Sam

**Comment by JonathanBrouwer** [comment]
Fixed in https://github.com/Bammerbom/UltimateCore/commit/f956cf290f2429a90363a2d168ba681ad5668df6

**Comment by sammyt291** [comment]
@Bammerbom Awesome, thank you for the quick fix,
Would it be possible to slide sethome as a priority over spawn also, and maybe let server owners choose the order of priority in the config?

Personally im looking for Spawn, Home, Bed as my priorities from lowest to highest.
