### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Sitherious** [Bammerbom/UltimateCore#12]
hey i notice you have a custom message for unknown command, love that feature, i really do could you also include you do not have permission! message as well? you already got 1 of my features im looking for in :)

https://forums.spongepowered.org/t/change-a-simple-message/16478/1

**Comment by JonathanBrouwer** [comment]
For UltimateCore commands you can change this message at "core.nopermissions" in the language file.
For other plugin's commands I am not going to add this because of technical reasons, sorry.
