### ISSUE TITLE
Pex

### ISSUE THREAD

**Issue by t0days** [Bammerbom/UltimateCore#13]
Is pex broken with your plugin because its not letting me use it.

**Comment by JonathanBrouwer** [comment]
I am using PermissionsEx with UltimateCore on my test server and everything is working fine. 
What plugins & mods are installed, and which version?
Which minecraft/sponge version?
How is it not letting you use it, is it erroring out or can't you change permissions or what?

**Comment by t0days** [comment]
Its just the prefixes that are fucked.

Sponge Version: **1.10.2-2202-5.1.0-BETA-2057**
UltimateCore Version: **3.0.3**
PermissionsEx Version: **2.0-SNAPSHOT-b147**

**Comment by t0days** [comment]
http://prntscr.com/dz1q6z

**Comment by t0days** [comment]
oh also I was trying to create a kit and its giving me an error, **"Error occurred while executing command: AIR"** This is the error that showed up in console, http://pastebin.com/D4naZc44

**Comment by JonathanBrouwer** [comment]
The prefixes are a known bug and this has already been fixed. The new version will come out soon.
Your second bug is a incompatibility between API 5 and API 6, which I fixed.
Thanks for reporting this bug
https://github.com/Bammerbom/UltimateCore/commit/ace87b30886c25d116aa12364302206d26101112
