### ISSUE TITLE
ClickInventory Error

### ISSUE THREAD

**Issue by Kaelico** [Bammerbom/UltimateCore#15]
Note: We were unable to figure out exactly what happened to cause this error after multiple test. It repeated this error 20 times before stopping.

Error: http://pastebin.com/LDKbWnzA

Minecraft 1.10.2
Forge 12.18.3.2215
Sponge 5.1.0 Beta 2070
UltimateCore 3.0.4 Alpha

**Comment by JonathanBrouwer** [comment]
I got this error earlier and I have no idea what us causing it. It randomly appears and just as randomly dissapears again.

**Comment by Kaelico** [comment]
Alright. I'll keep track of the logs and player events in hope to catch the cause. If I find anything I'll let you know.

**Comment by JonathanBrouwer** [comment]
Do you have any items blacklisted? (Using UC's blacklist module)

**Comment by Kaelico** [comment]
No.
Edit: Currently not using UC's blacklist module

**Comment by Kaelico** [comment]
Not sure if this helps. 

Modules Enabled:
AFK, Blacklist(Soon to be disabled), Broadcast, GeoIP, Inventory(Might disable after messing with it), ServerList, Spy, Tablist, UnknownCommand, Vanish, Votifier(Soon to be disabled)

**Comment by JonathanBrouwer** [comment]
Well the blacklist module causes the error here, so if you just want the error gone you can disable the module. Still wondering what causes it tho

**Comment by Kaelico** [comment]
I'll blacklist some items and have my players do random task until I get the error to replicate. Appreciate the work you put into this, so might as well help when I can.

**Comment by JonathanBrouwer** [comment]
I looked more into the sponge part of the error and it seems like Sponge is failing to get all inventory slots, or one inventory slot is somehow non-existent. Seems more like a Sponge bug and less like an UltimateCore bug, but I am not sure yet.
I will try to find what exactly is causing this later today.

EDIT: My guess is someone clicking in some kind of custom inventory or modded inventory. Do you have any mods installed?

**Comment by Kaelico** [comment]
Pixelmon. Which we've been messing with, trying to get that error to show up with no luck yet.
EDIT: Sorry about the delay. Router restarted at an awful time

**Comment by Kaelico** [comment]
Maybe good news?
We were able to replicate the bug and found the exact cause of it (At least when it comes to Pixelmon servers)
To replicate the bug:
- Throw pokemon away from you
- Press G to Forage the block next to you
- Pixelmon calls the event which attempts to give you the item
- Error shows in console

Error: http://pastebin.com/QGDvS8Ca

**Comment by JonathanBrouwer** [comment]
That is probably a Sponge or Pixelmon error, probably not UltimateCore.
Considering the stacktrace doesn't contain Pixelmon code, my guess is sponge.

All I do is call event.getTargetInventory().slots()
https://github.com/Bammerbom/UltimateCore/blob/master/src/main/java/bammerbom/ultimatecore/sponge/modules/blacklist/listeners/ItemListener.java#L81

I might make a SpongeCommon issue but I will ask first on the IRC what could be causing this.

**Comment by t0days** [comment]
Well this is the same problem with my server. When on yours @Kaelico when your player try and release Pokémon so they release. Mine aren't

**Comment by t0days** [comment]
It comes up with a big long error I have reported it to pixelmon devs waiting back

**Comment by Kaelico** [comment]
@t0days When the error first appears only the player who caused the event being called is unable to throw the Pokémon (At least from the test we've tried on the server). Your error might be caused by another method that we haven't found yet.

**Comment by t0days** [comment]
For me its all of the players. It will work for little less than 5 min when I restart but then after it it stops working.

**Comment by JonathanBrouwer** [comment]
This is a sponge issue, not one of UltimateCore.
Closed this, you can still reply here if you have any updates.
