### ISSUE TITLE
Kit error

### ISSUE THREAD

**Issue by EwoutV** [Bammerbom/UltimateCore#17]
Hello, suddenly, I get this error when using a kit: http://pasteboard.co/tWMjnv8kK.png

The error randomly appeared and then suddenly goes away again...

**Comment by JonathanBrouwer** [comment]
Fixed this already in https://github.com/Bammerbom/UltimateCore/commit/e874289abecbc09aa06dabc7e982602ff01a6641
You can download this build using 
https://www.mediafire.com/?2j4ki426o62m2mn
