### ISSUE TITLE
Gradle build fail: Could not find method findProperty() for arguments [url] on root project 'UltimateCore'

### ISSUE THREAD

**Issue by BobBond** [Bammerbom/UltimateCore#18]
##
__What went wrong__
Execution failed for task ':generateMetadata'.
> Could not find method findProperty() for arguments [url] on root project 'UltimateCore'.
##
__Environment__
**Linux** is Ubuntu 16.04 on Azure, **Java** is Oracle 1.8.0_121, **Gradle** is 2.10
Gradle 2.10
Build time:   2016-01-26 15:17:49 UTC
Build number: none
Revision:     UNKNOWN
Groovy:       2.4.5
Ant:          Apache Ant(TM) version 1.9.6 compiled on July 8 2015
JVM:          1.8.0_121 (Oracle Corporation 25.121-b13)
OS:           Linux 4.4.0-62-generic amd64
##
__Notes__ 
* Full error message below, debug and stacktrace logs attached. 
* This as SUDO, but also fails as root. 
* Both manually and creating/running gradlew instead, 
* I will look through logs for obvious issues (e.g. can I manually resolve the URI's from std CLI, etc)... but I'm *not a programmer* and it's my first time using Gradle.
* Any help appreciated

Bob

------- snip -----------
########################
########################
:blossomSourceReplacementJava
:generateMetadata FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateMetadata'.
> Could not find method findProperty() for arguments [url] on root project 'UltimateCore'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 10.349 secs
------- snip -----------

[debug_log.txt](https://github.com/Bammerbom/UltimateCore/files/800884/debug_log.txt)
[stacktrace_log.txt](https://github.com/Bammerbom/UltimateCore/files/800883/stacktrace_log.txt)

**Comment by JonathanBrouwer** [comment]
I am at Windows 10/Java 1.8.0_121 64 bits/Gradle 3.0
I tried cloning a new UltimateCore and building it using these commands
```
git clone https://github.com/Bammerbom/UltimateCore.git
cd UltimateCore
gradle build
```
And it worked.

I only know basic gradle so I am horrible at error solving.
Maybe try using Gradle 3 like me?
Maybe come to the UC discord so we can chat about this?

**Comment by BobBond** [comment]
Thanks for your swift response – and your efforts to make this plugin too. Seriously, big thanks. Without your plugin, Sponge is currently a lame duck IMHO.

* Very happy to chat on Discord and will login to the channel ASAP, but I'll try to be useful and investigate further first :-)  What is your timezone? I'm in AU, so UTC +11:00 (summertime) atm.

* Sounds like I used the same basic process as you. 

* I am actually a **Windows guy** so I'll build the same on a HyperV local server and compare the results. I host on Ubuntu on Azure because it's w-a-y cheaper :-)

* I'll try using Gradle 3.0. 

On that, AFAIK, the idea of the **gradle wrapper** is that my 'wrapped' build initiated from e.g. ./gradlew (gradle.bat on Windows) will prompt the system to download, install, run the gradle version you ran to build with. However I notice you've disabled/removed the wrapper in the .git transcript. Did it cause issues? If Gradle 3 solves the problem, maybe it's worth revisiting the wrapper thing? Happy to assist if possible on that. 

I also have an Ubuntu instance you can have sole access to if you want and I can also set you up with some free Azure hosting (on Ubuntu) long term if its of help. Happy to do the grunt work of setting up Java 8, maven, gradle, git, etc, etc too so you can jump on and *just* git-build-run. 

Will get back with results ASAP

**Comment by JonathanBrouwer** [comment]
* I am at UTC +1:00 (Netherlands), so that is basically the worst timezone to work together. We will get around it tho, I hope.
* I just (a few hours ago) added a gradle wrapper to the plugin, maybe that fixes it. I remember it causing errors but it was more than a year ago, so I just added it back and stuff worked.
* I am going to sleep in a few minutes, in about 10 hours I should be back. I am not sure how that works out with your timezone, but I should be around the whole sunday. (It is saturday 23:45 for me right now)
* I did get some errors with NuVotifier while building, I will try to fix them tomorrow. Also, I could give you an introduction to how the UltimateCore sourcecode works if you want to, but I really have to write docs on that soon.

**Comment by BobBond** [comment]
I'll be available when you're back early Sunday +1 so maybe we can catch up then. I'll report my findings in other posts, which you can ignore until then.

**Comment by BobBond** [comment]
Ubuntu ships with, or downloads Gradle 2.10 via the typical package updates i.e. 

(sudo) apt-get install gradle 

So, I've run: $>sudo apt-get remove gradle 

Running $>gradle -v 
now returns a "no such..." error, so it's a good time to test the gradlew file... it *should* download the correct version. If not, I'll manually get the 3.4 release and put it in the same spot (/usr/bin/gradle) the old one was. 

Thanks again, 

Bob

**Comment by JonathanBrouwer** [comment]
I am available, so if you need me you can come to the discord server so we can talk
Edit: I pushed some changes, the build should now fully work, the NuVotifier errors have been fixed

**Comment by BobBond** [comment]
I'm on now... (Monday AM) and will grab the new build, though I just downloaded the zip for Windows and it got further than my Linux build, but still failed. It couldn't find "tools.jar" if that helps. I also note that C:\[blah]\UltimateCore-master\build\tmp\compileJava is empty.... not what I'd expect? 

What's the discord channel please... I've only ever joined Discord by receiving/clicking an "invite".

**Comment by BobBond** [comment]
BTW, for completeness, the gradlew script on Linux is generated without Execute (x) permissions. 
The fix for that is:

$>sudo  chmod +x gradlew

Then you run

$> ./gradlew build

**Comment by BobBond** [comment]
Compile worked on Linux :-)
Doing the "school run", back online to test at 09:30 my time... maybe you'll still be around? 
I'll test the server as soon as I return and report.

**Comment by BobBond** [comment]
Hmmmm.... dumb question  (or failed build)... where is the .jar file I was expecting after the build located please? 

Actually, it appears the 'Build' ran fine but didn't do anything much (output below). 

I'll download the zip from Git, build it manually in a fresh directory and report back. Will do likewise on Windows 10/64 and Server 2016. 

------ snip ----------
root@mcserver:/var/games/minecraft/servers/ore# git clone https://github.com/Bammerbom/UltimateCore.git
Cloning into 'UltimateCore'...
remote: Counting objects: 28764, done.
remote: Compressing objects: 100% (107/107), done.
remote: Total 28764 (delta 44), reused 0 (delta 0), pack-reused 28645
Receiving objects: 100% (28764/28764), 41.35 MiB | 5.12 MiB/s, done.
Resolving deltas: 100% (16455/16455), done.
Checking connectivity... done.
root@mcserver:/var/games/minecraft/servers/ore# cd UltimateCore
root@mcserver:/var/games/minecraft/servers/ore/UltimateCore# chmod +x gradlew
root@mcserver:/var/games/minecraft/servers/ore/UltimateCore# ./gradlew build
Starting a Gradle Daemon (subsequent builds will be faster)
########################
## Powered by Blossom ##
########################
:blossomSourceReplacementJava
:generateMetadata
:compileJava
Download https://dl.bintray.com/nuvotifier/maven/com/vexsoftware/nuvotifier-universal/2.3.4/nuvotifier-universal-2.3.4.pom
Download https://dl.bintray.com/nuvotifier/maven/com/vexsoftware/nuvotifier/2.3.4/nuvotifier-2.3.4.pom
Download https://dl.bintray.com/nuvotifier/maven/com/vexsoftware/nuvotifier-universal/2.3.4/nuvotifier-universal-2.3.4.jar
Download https://repo1.maven.org/maven2/org/json/json/20080701/json-20080701.jar
Note: Reading extra plugin metadata from /var/games/minecraft/servers/ore/UltimateCore/build/tmp/generateMetadata/mcmod.info
Note: Writing plugin metadata to /var/games/minecraft/servers/ore/UltimateCore/build/tmp/generateMetadata/mcmod.info
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:processResources
:classes
:jar
:assemble
:compileTestJava NO-SOURCE
:processTestResources NO-SOURCE
:testClasses UP-TO-DATE
:test NO-SOURCE
:check UP-TO-DATE
:shadowJar
:build

BUILD SUCCESSFUL

Total time: 1 mins 7.318 secs
root@mcserver:/var/games/minecraft/servers/ore/UltimateCore# ls
build  build.gradle  docs  gradle  gradlew  gradlew.bat  LICENSE.txt  README.md  settings.gradle  src
------ snip ----------

**Comment by JonathanBrouwer** [comment]
The discord is https://discord.gg/ymEQE3s

Seems like your build is completely successfull tho.
The jar should be located at /build/libs/UltimateCore.jar
