### ISSUE TITLE
Line breaking doesn't work

### ISSUE THREAD

**Issue by TomberWolf** [Bammerbom/UltimateCore#22]
Line breaking with \n doesn't work for automessages.

**Comment by JonathanBrouwer** [comment]
It does for me.
Could you give me a little more details? (OS, Sponge version, Config, Etc)

**Comment by TomberWolf** [comment]
Sorry!
Here you go:

spongeforge-1.10.2-2254-5.2.0-BETA-2259
forge-1.10.2-12.18.3.2254-universal
UltimateCore-3.0.9
Using the default automessage.conf

![javaw 2017-03-30 13-49-47-885](https://cloud.githubusercontent.com/assets/9993839/24502960/594c58fe-1550-11e7-8c69-3a9b6fd904a7.jpg)

**Comment by JonathanBrouwer** [comment]
Confirmed.
Will fix this later today

**Comment by JonathanBrouwer** [comment]
Download: http://www.mediafire.com/file/2j4ki426o62m2mn/UltimateCore.jar
(Sorry for the small delay btw)

**Comment by TomberWolf** [comment]
Don't worry about it. It works! Thanks for fixing :-)
