### ISSUE TITLE
Blank skins

### ISSUE THREAD

**Issue by SweetAurora** [Bammerbom/UltimateCore#24]
I started to use the ultimate core becouse it looked very good and it is! but i have 1 problem... i can't see any persones skin... is it in the config becouse i can't find anything that blocks skins. and i have 1 idea. my idea is that you can edit what stands in the chat when you use /broadcast.

**Comment by JonathanBrouwer** [comment]
Try enabling 'compatibility mode' in the tablist config
And you can edit what is in front of the /broadcast in the broadcast.conf

**Comment by SweetAurora** [comment]
I found the broadcast menu already but i am waiting till one of my friends join again then i can see if it worked

**Comment by JonathanBrouwer** [comment]
I will close this issue for now.
If it still doesn't work please leave a message here and I will re-open it
