### ISSUE TITLE
\back doesn't work "No location found to go back to"

### ISSUE THREAD

**Issue by Faryzal2020** [Bammerbom/UltimateCore#25]
i've put both permission for back and back ondeath but still doesn't work in any conditions.
i'm using the latest UltimateCore, other plugins that i use are redprotect, luckperms, economylite, and flexibleLogin.
spongeforge 5.2.0 beta 2264

**Comment by Faryzal2020** [comment]
i'm sorry i typo'd the spongeforge version, its spongeforge 5.2.0 BETA build 2272 for forge 2254

**Comment by JonathanBrouwer** [comment]
I will make a fix for this issue this weekend
