### ISSUE TITLE
Could not pass ClickInventoryEvent$Primary$Impl to Plugin

### ISSUE THREAD

**Issue by Faryzal2020** [Bammerbom/UltimateCore#26]
so in my modpack server i'm using Nucleus and UltimateCore, in UC i use just some of the modules that nucleus doesn't have like serverlist.
both nucleus and uc made (?) this error in console https://pastebin.com/WW3MfRHK , sometimes spammed, im not sure what caused it and what it causes.. but i've tested that the error shows up in the console when using Architecture Craft mod Saw Bench when taking the crafting result from the bench when holding something. Also it makes me cant spam click the crafting result, sometimes i cant take/get the crafting result. but the error also shows up by something else that i cant find, though im pretty sure its always related to a player interacting with some mod block stuff..
server using spongeforge 5.2.0 for forge 2254
with the latest UC

**Comment by JonathanBrouwer** [comment]
This issue is caused by the mod, but I will just ignore any error at my side because I saw this problem earlier and it seems like sponge is not handling inventory correctly
