### ISSUE TITLE
Feature request: Expand width of tablist

### ISSUE THREAD

**Issue by TomberWolf** [Bammerbom/UltimateCore#27]
Hey,

do you think you could expand the width of the tablist so that we can add and show more infos behind the player names?

**Comment by JonathanBrouwer** [comment]
Do you mean extra information in new boxes? I could do this but I don't really have time for it now. I will add this later

**Comment by TomberWolf** [comment]
No need for adding new boxes. Just the width of the user box (maybe dynamic?).

Just an example for our format: "&e%displayname% (%name%) [%world%]"
So it's cutted off after the displayname in most cases.

**Comment by JonathanBrouwer** [comment]
It should not be cut off.
Are you using compatibility mode?
If so, try turning it off.
If not so, what are your sponge/minecraft/uc versions?

**Comment by TomberWolf** [comment]
I'm not using compatibility mode.

- forge-1.10.2-12.18.3.2281-universal
- spongeforge-1.10.2-2281-5.2.0-BETA-2274
- UltimateCore-3.0.9

Please notice that I'm using the UC version you've fixed for me because of the missed line break issue https://github.com/Bammerbom/UltimateCore/issues/22.

**Comment by JonathanBrouwer** [comment]
Download: http://www.mediafire.com/file/2j4ki426o62m2mn/UltimateCore.jar
Note that if you encounter any problems and you want faster support, you can join our discord at https://discord.gg/ymEQE3s

**Comment by TomberWolf** [comment]
Thanks for your fast response.
I would prefer GitHub so that other users can track issues and fixes, too.
Are you going to update / release the fixes in a new version, too?
It's now a little bit confusing. 👍

**Comment by JonathanBrouwer** [comment]
I will release a build pretty soon, yeah
