### ISSUE TITLE
Error (Failed to initialize module votifier)

### ISSUE THREAD

**Issue by ghost** [Bammerbom/UltimateCore#28]
[2017-04-24_23-02-18-694.txt](https://github.com/Bammerbom/UltimateCore/files/952991/2017-04-24_23-02-18-694.txt)

Thank you a lot for help!

**Comment by JonathanBrouwer** [comment]
Could you upload your votifier config?
Seems like a syntax error in the config

**Comment by ghost** [comment]
Hey, @Bammerbom! Thank you a lot for the help! Your plugin is truly amazing, just like you! :D 

Here is the file:

[votifier.txt](https://github.com/Bammerbom/UltimateCore/files/955380/votifier.txt)

Thank you!

**Comment by JonathanBrouwer** [comment]
Reproduced.

**Comment by JonathanBrouwer** [comment]
Download: http://www.mediafire.com/file/2j4ki426o62m2mn/UltimateCore.jar

**Comment by ghost** [comment]
Thank you ;)
