### ISSUE TITLE
latest does not compile

### ISSUE THREAD

**Issue by insert3coins** [Bammerbom/UltimateCore#4]
[INFO] Scanning for projects...
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building UltimateCore 2.0.5
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for net.ess3:Essentials:jar:2.14-20140906.162642-94 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for com.massivecraft:Factions:jar:2.7.5 is missing, no dependency information available
[WARNING] The POM for com.massivecraft:MassiveCore:jar:2.7.5 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ UltimateCore ---
[INFO] Deleting D:\Programming\minecraft\UltimateCore\target
[INFO] 
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ UltimateCore ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 9 resources to .
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ UltimateCore ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 204 source files to D:\Programming\minecraft\UltimateCore\target\classes
[INFO] /D:/Programming/minecraft/UltimateCore/src/main/java/bammerbom/ultimatecore/bukkit/resources/utils/AttributeUtil.java: Some input files use or override a deprecated API.
[INFO] /D:/Programming/minecraft/UltimateCore/src/main/java/bammerbom/ultimatecore/bukkit/resources/utils/AttributeUtil.java: Recompile with -Xlint:deprecation for details.
[INFO] /D:/Programming/minecraft/UltimateCore/src/main/java/bammerbom/ultimatecore/bukkit/r.java: Some input files use unchecked or unsafe operations.
[INFO] /D:/Programming/minecraft/UltimateCore/src/main/java/bammerbom/ultimatecore/bukkit/r.java: Recompile with -Xlint:unchecked for details.
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /D:/Programming/minecraft/UltimateCore/src/main/java/bammerbom/ultimatecore/bukkit/resources/utils/LocationUtil.java:[204,29] reference to getTargetBlock is ambiguous, both method getTargetBlock(java.util.HashSet<java.lang.Byte>,int) in org.bukkit.entity.LivingEntity and method getTargetBlock(java.util.Set<org.bukkit.Material>,int) in org.bukkit.entity.LivingEntity match
[ERROR] /D:/Programming/minecraft/UltimateCore/src/main/java/bammerbom/ultimatecore/bukkit/commands/CmdSpawner.java:[68,20] reference to getTargetBlock is ambiguous, both method getTargetBlock(java.util.HashSet<java.lang.Byte>,int) in org.bukkit.entity.LivingEntity and method getTargetBlock(java.util.Set<org.bukkit.Material>,int) in org.bukkit.entity.LivingEntity match
[ERROR] /D:/Programming/minecraft/UltimateCore/src/main/java/bammerbom/ultimatecore/bukkit/commands/CmdSmite.java:[77,29] reference to getTargetBlock is ambiguous, both method getTargetBlock(java.util.HashSet<java.lang.Byte>,int) in org.bukkit.entity.LivingEntity and method getTargetBlock(java.util.Set<org.bukkit.Material>,int) in org.bukkit.entity.LivingEntity match
[ERROR] /D:/Programming/minecraft/UltimateCore/src/main/java/bammerbom/ultimatecore/bukkit/commands/CmdMegasmite.java:[81,29] reference to getTargetBlock is ambiguous, both method getTargetBlock(java.util.HashSet<java.lang.Byte>,int) in org.bukkit.entity.LivingEntity and method getTargetBlock(java.util.Set<org.bukkit.Material>,int) in org.bukkit.entity.LivingEntity match
[INFO] 4 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.825 s
[INFO] Finished at: 2015-02-17T10:10:01+13:00
[INFO] Final Memory: 20M/457M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:compile (default-compile) on project UltimateCore: Compilation failure: Compilation failure:
[ERROR] /D:/Programming/minecraft/UltimateCore/src/main/java/bammerbom/ultimatecore/bukkit/resources/utils/LocationUtil.java:[204,29] reference to getTargetBlock is ambiguous, both method getTargetBlock(java.util.HashSet<java.lang.Byte>,int) in org.bukkit.entity.LivingEntity and method getTargetBlock(java.util.Set<org.bukkit.Material>,int) in org.bukkit.entity.LivingEntity match
[ERROR] /D:/Programming/minecraft/UltimateCore/src/main/java/bammerbom/ultimatecore/bukkit/commands/CmdSpawner.java:[68,20] reference to getTargetBlock is ambiguous, both method getTargetBlock(java.util.HashSet<java.lang.Byte>,int) in org.bukkit.entity.LivingEntity and method getTargetBlock(java.util.Set<org.bukkit.Material>,int) in org.bukkit.entity.LivingEntity match
[ERROR] /D:/Programming/minecraft/UltimateCore/src/main/java/bammerbom/ultimatecore/bukkit/commands/CmdSmite.java:[77,29] reference to getTargetBlock is ambiguous, both method getTargetBlock(java.util.HashSet<java.lang.Byte>,int) in org.bukkit.entity.LivingEntity and method getTargetBlock(java.util.Set<org.bukkit.Material>,int) in org.bukkit.entity.LivingEntity match
[ERROR] /D:/Programming/minecraft/UltimateCore/src/main/java/bammerbom/ultimatecore/bukkit/commands/CmdMegasmite.java:[81,29] reference to getTargetBlock is ambiguous, both method getTargetBlock(java.util.HashSet<java.lang.Byte>,int) in org.bukkit.entity.LivingEntity and method getTargetBlock(java.util.Set<org.bukkit.Material>,int) in org.bukkit.entity.LivingEntity match
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by JonathanBrouwer** [comment]
Probarly fixed.

Comment here if the fix doesn't work as it builds fine for me but I think your maven is configured a little but stricter.

**Comment by insert3coins** [comment]
still does not compile...

default maven not changed anything... compile options with mvn clean install 

log: 

[INFO] Scanning for projects...
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building UltimateCore 2.0.6
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for net.ess3:Essentials:jar:2.14-20140906.162642-94 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for com.massivecraft:Factions:jar:2.7.5 is missing, no dependency information available
[WARNING] The POM for com.massivecraft:MassiveCore:jar:2.7.5 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ UltimateCore ---
[INFO] Deleting D:\Programming\minecraft\UltimateCore\target
[INFO] 
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ UltimateCore ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 9 resources to .
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ UltimateCore ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 204 source files to D:\Programming\minecraft\UltimateCore\target\classes
[INFO] /D:/Programming/minecraft/UltimateCore/src/main/java/bammerbom/ultimatecore/bukkit/resources/utils/AttributeUtil.java: Some input files use or override a deprecated API.
[INFO] /D:/Programming/minecraft/UltimateCore/src/main/java/bammerbom/ultimatecore/bukkit/resources/utils/AttributeUtil.java: Recompile with -Xlint:deprecation for details.
[INFO] /D:/Programming/minecraft/UltimateCore/src/main/java/bammerbom/ultimatecore/bukkit/r.java: Some input files use unchecked or unsafe operations.
[INFO] /D:/Programming/minecraft/UltimateCore/src/main/java/bammerbom/ultimatecore/bukkit/r.java: Recompile with -Xlint:unchecked for details.
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /D:/Programming/minecraft/UltimateCore/src/main/java/bammerbom/ultimatecore/bukkit/resources/utils/LocationUtil.java:[204,29] reference to getTargetBlock is ambiguous, both method getTargetBlock(java.util.HashSet<java.lang.Byte>,int) in org.bukkit.entity.LivingEntity and method getTargetBlock(java.util.Set<org.bukkit.Material>,int) in org.bukkit.entity.LivingEntity match
[ERROR] /D:/Programming/minecraft/UltimateCore/src/main/java/bammerbom/ultimatecore/bukkit/commands/CmdSpawner.java:[69,20] reference to getTargetBlock is ambiguous, both method getTargetBlock(java.util.HashSet<java.lang.Byte>,int) in org.bukkit.entity.LivingEntity and method getTargetBlock(java.util.Set<org.bukkit.Material>,int) in org.bukkit.entity.LivingEntity match
[ERROR] /D:/Programming/minecraft/UltimateCore/src/main/java/bammerbom/ultimatecore/bukkit/commands/CmdSmite.java:[78,29] reference to getTargetBlock is ambiguous, both method getTargetBlock(java.util.HashSet<java.lang.Byte>,int) in org.bukkit.entity.LivingEntity and method getTargetBlock(java.util.Set<org.bukkit.Material>,int) in org.bukkit.entity.LivingEntity match
[ERROR] /D:/Programming/minecraft/UltimateCore/src/main/java/bammerbom/ultimatecore/bukkit/commands/CmdMegasmite.java:[82,29] reference to getTargetBlock is ambiguous, both method getTargetBlock(java.util.HashSet<java.lang.Byte>,int) in org.bukkit.entity.LivingEntity and method getTargetBlock(java.util.Set<org.bukkit.Material>,int) in org.bukkit.entity.LivingEntity match
[INFO] 4 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.700 s
[INFO] Finished at: 2015-02-18T07:10:08+13:00
[INFO] Final Memory: 20M/446M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:compile (default-compile) on project UltimateCore: Compilation failure: Compilation failure:
[ERROR] /D:/Programming/minecraft/UltimateCore/src/main/java/bammerbom/ultimatecore/bukkit/resources/utils/LocationUtil.java:[204,29] reference to getTargetBlock is ambiguous, both method getTargetBlock(java.util.HashSet<java.lang.Byte>,int) in org.bukkit.entity.LivingEntity and method getTargetBlock(java.util.Set<org.bukkit.Material>,int) in org.bukkit.entity.LivingEntity match
[ERROR] /D:/Programming/minecraft/UltimateCore/src/main/java/bammerbom/ultimatecore/bukkit/commands/CmdSpawner.java:[69,20] reference to getTargetBlock is ambiguous, both method getTargetBlock(java.util.HashSet<java.lang.Byte>,int) in org.bukkit.entity.LivingEntity and method getTargetBlock(java.util.Set<org.bukkit.Material>,int) in org.bukkit.entity.LivingEntity match
[ERROR] /D:/Programming/minecraft/UltimateCore/src/main/java/bammerbom/ultimatecore/bukkit/commands/CmdSmite.java:[78,29] reference to getTargetBlock is ambiguous, both method getTargetBlock(java.util.HashSet<java.lang.Byte>,int) in org.bukkit.entity.LivingEntity and method getTargetBlock(java.util.Set<org.bukkit.Material>,int) in org.bukkit.entity.LivingEntity match
[ERROR] /D:/Programming/minecraft/UltimateCore/src/main/java/bammerbom/ultimatecore/bukkit/commands/CmdMegasmite.java:[82,29] reference to getTargetBlock is ambiguous, both method getTargetBlock(java.util.HashSet<java.lang.Byte>,int) in org.bukkit.entity.LivingEntity and method getTargetBlock(java.util.Set<org.bukkit.Material>,int) in org.bukkit.entity.LivingEntity match
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by JonathanBrouwer** [comment]
Fixed.
